#!/usr/local/var/rbenv/shims/ruby

ENV['RBENV_ROOT'] ||= '/usr/local/var/rbenv'
`which rbenv > /dev/null 2>&1`
if $?.success?
  `eval "$(rbenv init -)"`
end

require 'oj'
require 'colorize'
require 'bundler'

def log_success(message)
  puts message.green
end

def log_error(message)
  puts message.red
end

def get_local_npm_path(package_name, project_dir)
  potential_path = File.join(project_dir, 'node_modules', package_name)
  return potential_path if File.directory?(potential_path)
  nil
end

def prompt_for_inclusion(package_name, modify_mode, package_statuses)
  previous_choice = package_statuses[package_name][:enabled] ? 'y' : 'n'
  return package_statuses[package_name][:enabled] unless modify_mode || !package_statuses.key?(package_name)

  print "Include #{package_name} in embeddings? [#{previous_choice}]: "
  decision = STDIN.gets.chomp.downcase
  decision = previous_choice if decision.empty?
  decision == 'y'
end

modify_mode = ARGV.include?('-m') || ARGV.include?('--modify')

status_file = 'packages_status.json'
package_statuses = File.exist?(status_file) ? Oj.load(File.read(status_file)) : {}

# Validate the structure of the package_statuses
package_statuses.each do |package, details|
  unless details.is_a?(Hash) && details.key?(:path) && details.key?(:enabled)
    package_statuses = {} # Reset if the structure is not as expected
    break
  end
end

if File.exist?('Gemfile')
  log_success("Gemfile found. Processing...")
  
  unless system('bundle check')
    log_error("Some gems are missing. Please run 'bundle install' and try again.")
    exit
  end
  
  Bundler.load.specs.each do |spec|
    local_path = spec.full_gem_path
    gem_name = spec.name

    if local_path && File.directory?(local_path)
      log_success("Found local path for gem #{gem_name}: #{local_path}")
      package_statuses[gem_name] = { path: local_path, enabled: prompt_for_inclusion(gem_name, modify_mode, package_statuses) }
    else
      log_error("Local path not found for gem: #{gem_name}")
    end
  end
elsif File.exist?('package.json')
  log_success("package.json found. Processing...")
  packages = Oj.load(File.read('package.json'))['dependencies']
  project_dir = Dir.pwd
  packages.each do |package_name, _version|
    local_path = get_local_npm_path(package_name, project_dir)
    if local_path
      log_success("Found local path for npm package #{package_name}: #{local_path}")
      package_statuses[package_name] = { path: local_path, enabled: prompt_for_inclusion(package_name, modify_mode, package_statuses) }
    else
      log_error("Local path not found for npm package: #{package_name}. Ensure the package is installed using 'npm install #{package_name}' or 'yarn add #{package_name}' if you're using Yarn.")
    end
  end
else
  log_error("Neither Gemfile nor package.json found in the current directory.")
end

File.write(status_file, Oj.dump(package_statuses))

require_relative 'create_embeddings'
